### ISSUE TITLE
glasi

### ISSUE THREAD

**Issue by valisstyle** [glaser-alex/az#1]
### hi @glaser-alex 
willst du mit mir gehen?

LG
deine geheime Verehrerin

PS:
du hast ein tolles profil, ich **liebe** aber noch mehr deine website und deine haare ^^
bussiii<3

**Comment by glaser-alex** [comment]
hi @valisstyle 
vllt können wir ja einfach über github schreiben

**Comment by valisstyle** [comment]
ich wusste gar nicht, dass du schreiben geschweige denn lesen kannst...

**Comment by valisstyle** [comment]
aber ok wie du meinst

**Comment by glaser-alex** [comment]
> ### hi @glaser-alex
> willst du mit mir gehen?
> 
> LG deine geheime Verehrerin
> 
> PS: du hast ein tolles profil, ich **liebe** aber noch mehr deine website und deine haare ^^ bussiii<3

Toll was du mir da geschrieben hast. Hab mich sehr gefreut. süß

**Comment by valisstyle** [comment]
ich weiß danke 👯‍♂️

**Comment by valisstyle** [comment]
also erzähl was hat deine omi gesagt?

**Comment by glaser-alex** [comment]
die frage ist jetzt ob ich lust habe

**Comment by valisstyle** [comment]
boah keine ahnung ob ich das darf, alkohol oder was

**Comment by valisstyle** [comment]
mit bezahlung vielleicht

**Comment by valisstyle** [comment]
aber am nächsten tag hast du fußball oder 
aiso zeitlich gehts schon, aber bis nach tüßling fahren und dann nichts dafür bekommen lohnt sich ja schon von den benzinkosten her nicht

**Comment by valisstyle** [comment]
außerdem bin ich im ausschenken eher schlecht, besser im kellnern etc, weil ich nie genau weiß wie man was mischt

**Comment by glaser-alex** [comment]
ja ich hab auch echt wenig plan davon aber was sag ich meiner Oma? ich hätte ja normalerweise zeit.

**Comment by valisstyle** [comment]
ja sag ihr halt dass du nicht sicher bist, was genau du mischen sollst und das wenn das ohne bezahlung blöd ist, wegen den benzinkosten oder ist das blöd für dich zu fragen?

**Comment by valisstyle** [comment]
was ist das denn für ein event?

**Comment by glaser-alex** [comment]
ich bin mir nicht mehr sicher ich wusse ich werde es vergessen

**Comment by glaser-alex** [comment]
ich hab ja nochmal zur sicherheit nachgefragt, weil ich wusste, dass du es wissen willst aber jetzt hab ich es schon wieder vergessen

**Comment by valisstyle** [comment]
wann willst du wegen dem Wochenend thema reden, muss nämlich bald zum Bahnhof

**Comment by glaser-alex** [comment]
du kanns gerne von deinem plan erzählen weil ich keine gedanken lesen kann

**Comment by valisstyle** [comment]
also ich muss am samstag von 8:30Uhr bis ich schätze 11:30Uhr oder so schnell ich halt gehen kann zu Feuerwehr 
zu hast aber Samstag Fußball 
ich dachte wir könnten es so machen, dass du zu mir kommst am Freitag ich dann Samstag dann gemeinsam zu dir wegen Fußball und dann können wir ja immer noch Volksfest oder Poolparty beim Simon oder iwas anderes machen

**Comment by valisstyle** [comment]
ok ich packe jetzt zusammen, kannst mir ja deine antwort hier oder auf Whatsapp schicken bye
